name: CI with spack
run-name: Ubuntu 22.04
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Spack
      uses: spack/setup-spack@v2
    
    - name: Install
      run: |
        spack repo add ./rdkit-spack 
        spack -e . install --no-check-signature --test=root

    - name: Run
      shell: spack-bash {0}
      run: |    
        spack env activate .
        spack cd rdkit-spack
        make test
        
    - name: Archive spack logs
      uses: actions/upload-artifact@v4
      with:
        name: Spack logs
        path: /tmp/runner/spack-stage/
    
    - name: Push packages and update index
      run: |
        spack -e . mirror set --push --oci-username ${{ github.actor }} --oci-password "${{ secrets.GITHUB_TOKEN }}" local-buildcache
        spack -e . buildcache push --base-image ubuntu:22.04 --update-index local-buildcache
      if: ${{ !cancelled() }}
